version: "3.9"

services:
  frontend:
    # Build from Dockerfile
    # Note: comment `image`
    #
    # build:
    #   context: .
    #   dockerfile: ./docker/web/Dockerfile.prod
    image: twylix/luna_frontend
    container_name: frontend
    volumes:
      - static_data:/var/www/luna.staypony.space/static/
    env_file:
      - ./.env.production
    networks:
      - luna_network

  nginx_frontend:
    # Build from Dockerfile
    # Note: comment `image`
    #
    # build:
    #   context: .
    #   dockerfile: ./docker/nginx/Dockerfile.prod
    image: twylix/luna_frontend_nginx
    container_name: nginx_frontend
    volumes:
      - static_data:/var/www/luna.staypony.space/static
    depends_on:
      - frontend
    networks:
      - luna_network
    ports:
      - 8080:80
      - 8443:443

volumes:
  static_data:


networks:
  luna_network:
    driver: bridge
    name: luna_network
