version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.dev
    container_name: frontend
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
