# Pull image
FROM python:3.9.8-alpine3.14

# Set workdir
WORKDIR /usr/src/luna

# Env vars
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copy project
COPY . .

# Project dependencies
RUN apk update
RUN apk add linux-headers postgresql-dev gcc make libpq python3-dev musl-dev libffi-dev curl git
RUN python -m pip install poetry 
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-dev

RUN sed -i 's/\r$//g' /usr/src/luna/docker/app/entrypoint.dev.sh
RUN chmod +x /usr/src/luna/docker/app/entrypoint.dev.sh

# Entrypoint
ENTRYPOINT ["/bin/sh", "/usr/src/luna/docker/app/entrypoint.dev.sh"]