FROM nginx:1.22.0

RUN rm /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/nginx.conf /etc/nginx/conf.d
COPY ./ssl/cert.crt /etc/ssl/certs/cert.crt
COPY ./ssl/private.key /etc/ssl/private/private.key